### ISSUE TITLE
TypeScript support?

### ISSUE THREAD

**Issue by Voodu** [alexkuc/chartjs-plugin-doughnutlabel-rebourne#5]
Hi,

Do you plan on adding TypeScript support for this fork?

**Comment by alexkuc** [comment]
@Voodu to be honest, I have quite a busy schedule at the moment. If someone could assist with that, would be really great.

**Comment by Voodu** [comment]
I made a [PR to DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/61062). Maybe you want to take a look and do a [quick review](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/61062/files) to make sure it's ok from your perspective?

I'd be also happy to add you as another owner of the types if you wish.

**Comment by alexkuc** [comment]
@Voodu I saw your comment regarding types PR but, unfortunately, was too busy and couldn't reply until now. I see that your PR was merged and all is good. As I understand this issue can be considered resolved now? 

Also, I would be more than happy if you could update `README.md` and add note regarding types. After all, you did all the heavy lifting with the types so it's only fair that you "put the icing on the cake" by updating `README.md`.

**Comment by Voodu** [comment]
Yes, types seem to work fine.
Sorry for deleting the comment; the PR got reviewed and merged so quickly, that the comment here got outdated after a day.
I created the PR with the updated README and I'm closing this issue.
